FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
COPY ./requirements.txt /requirements.txt
COPY ./serviceAccount.json /serviceAccount.json
ENV GOOGLE_APPLICATION_CREDENTIALS /serviceAccount.json
RUN pip install -r /requirements.txt